[package]
name = "virtual_machine"
version = "0.1.0"
edition = "2021"

[dependencies]
# Error handling
thiserror = "1.0"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Parser combinators (we'll need this later for assembler)
nom = "7.1"
bytes = "1.9.0"